name = "ExponentialAction"
uuid = "e24c0720-ea99-47e8-929e-571b494574d3"
authors = ["Seth Axen <seth.axen@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
